export const enum ENVIRONMENT_CONFIG {
  FIREBASE_API_KEY = 'FIREBASE_API_KEY',
  FIREBASE_AUTH_BASE_URL = 'FIREBASE_AUTH_BASE_URL',
  RANDOM_AVATAR = 'RANDOM_AVATAR',
  BASE_DB_URL = 'BASE_DB_URL',
}
